### ISSUE TITLE
A very long value in a string. Invalid URI: The Uri string is too long.

### ISSUE THREAD

**Issue by ktb-dev** [denis-ivanov/EntityFrameworkCore.ClickHouse#23]
```c#
class MyTable
{
       public string Txt => "a very very long value .........";
}

var item = new MyTable();

var _dbSet = _dbContext.Set<MyTable>();
await _dbSet.AddAsync(item);
await _dbContext.SaveChangesAsync();
```

when I use EntityFramework, and I try to insert an object into the table that has a string type property and this property has a very long value, then I get this error: 

> _**exception.InnerException.Message** => Invalid URI: The Uri string is too long._

>_**exception.InnerException.StackTrace** =>_
>>_at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
at System.Uri..ctor(String uriString, UriKind uriKind)
at System.Net.Http.HttpRequestMessage..ctor(HttpMethod method, String requestUri)
at ClickHouse.Client.ADO.ClickHouseCommand.<PostSqlQueryAsync>d__54.MoveNext()
at ClickHouse.Client.ADO.ClickHouseCommand.<ExecuteDbDataReaderAsync>d__53.MoveNext()
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__19.MoveNext()
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__19.MoveNext()
at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.<ExecuteAsync>d__50.MoveNext()_

but, if you use this method, then everything works out successfully:
```c#
using var bulkCopy = new ClickHouseBulkCopy(connection)
{
      DestinationTableName = "mytable",
      BatchSize = 1
};

var list = (new List<object[]>() { new object[] { item.Txt } });
await bulkCopy.WriteToServerAsync(list);
``` 
as I understand it, this method generates the following query: 
```sql
INSERT INTO {DestinationTableName} ({string.Join(", ", columnNames)}) FORMAT RowBinary;
``` 

is there a way to execute a query using ORM?

**Comment by denis-ivanov** [comment]
Please, try a new version [EntityFrameworkCore.ClickHouse/0.0.12](https://www.nuget.org/packages/EntityFrameworkCore.ClickHouse/0.0.12) and if it's still reproducible provide a minimum working example.
