### ISSUE TITLE
insert entity failed with 'not implement exception'

### ISSUE THREAD

**Issue by timiil** [denis-ivanov/EntityFrameworkCore.ClickHouse#7]
hi, i had use dotnet 5 to make a simple demo,

```
public class ClickHouseContext : DbContext
    {
        public DbSet<SalesOrder> SalesOrders { get; set; }

        //public DbSet<StoreConfig> StoreConfigs { get; set; }

        private readonly string connectionString;

        public ClickHouseContext(string connectionString)
        {
            this.connectionString = connectionString;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<SalesOrder>().HasKey(e => e.Id);
            //modelBuilder.Entity<StoreConfig>().HasKey(e => e.Id);


            modelBuilder.Entity<SalesOrder>()
                .HasMergeTreeEngine(new Expression<Func<SalesOrder, object>>[]
                {
                        e => e.Id
                });
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //optionsBuilder.LogTo(ClickHouseContext.WriteLine);
            optionsBuilder.UseClickHouse(this.connectionString);
        }
    }

```

```
POCO.SalesOrder so = new POCO.SalesOrder() { Id = 0, SheetID = "11aa" };
string cnstr = "Host=192.168.1.43;Port=9090;User=default;Password=by123456";
EF.ClickHouseContext ctx = new EF.ClickHouseContext(cnstr);

ctx.Database.EnsureCreated();   //it is ok here,the table had been created.

ctx.SalesOrders.Add(so);
var ret = ctx.SaveChanges();  //failed here 
```

the stacktrace is :

```
   at ClickHouse.EntityFrameworkCore.Update.Internal.ClickHouseUpdateSqlGenerator.AppendRowsAffectedWhereCondition(StringBuilder commandStringBuilder, Int32 expectedRowsAffected)
   at Microsoft.EntityFrameworkCore.Update.UpdateSqlGenerator.AppendWhereAffectedClause(StringBuilder commandStringBuilder, IReadOnlyList`1 operations)
   at Microsoft.EntityFrameworkCore.Update.UpdateSqlGenerator.AppendSelectAffectedCommand(StringBuilder commandStringBuilder, String name, String schema, IReadOnlyList`1 readOperations, IReadOnlyList`1 conditionOperations, Int32 commandPosition)
   at Microsoft.EntityFrameworkCore.Update.UpdateSqlGenerator.AppendInsertOperation(StringBuilder commandStringBuilder, ModificationCommand command, Int32 commandPosition)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.UpdateCachedCommandText(Int32 commandPosition)
   at ClickHouse.EntityFrameworkCore.Update.Internal.ClickHouseModificationCommandBatch.GetCommandText()
   at ClickHouse.EntityFrameworkCore.Update.Internal.ClickHouseModificationCommandBatch.CreateStoreCommand()
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(DbContext _, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at bytt.clickhouse.demo.Program.Main(String[] args) in D:\code\bytt\bytt.clickhouse.demo\Program.cs:line 27

```

any idea ? very thanks!

**Comment by denis-ivanov** [comment]
Hi, @timiil !

Can you provide a minimal working example? I need to see `SalesOrder` and `StoreConfig` classes.
Thanks!

**Comment by timiil** [comment]
> 
> 
> Hi, @timiil !
> 
> Can you provide a minimal working example? I need to see `SalesOrder` and `StoreConfig` classes.
> Thanks!

hi , i had 'fixed' the problem, the new Entity 

```
POCO.SalesOrder so = new POCO.SalesOrder() { Id = 0, SheetID = "11aa" };   //failed

```
is failed, but when the 'Id' field it is larger than zero, it is ok.

```
POCO.SalesOrder so = new POCO.SalesOrder() { Id = 1, SheetID = "11aa" };   //it is ok now
```

i had write a short example in the other issue, thanks and let us close this issue :)

**Comment by denis-ivanov** [comment]
ClickHouse doesn't provide auto increment columns, that's why you should provider primary keys by yourself.
